server:
  port: 8081

spring:
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5434/nostra_cinema
    username: postgres
    password: admin

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

minio:
  url: http://127.0.0.1:9000
#  access-key: hZFlRUmGv7AbixjasmEh
#  secret-key: mm8fSd7YECQlGPMBY5kycG9crTdWQqefwmyxcVXa
  bucket-name: nostra-cinema
  access-key: minioadmin
  secret-key: minioadmin


email:
  sender: admin-nostracinema@gmail.com
  subject: OTP code Nostra Cinema
  template: "This is the OTP code nostra Cinema: %s Please do not share this code with anyone."
  username: 6d7b0805389bf6
  password: 2720e0195a02da
  smtp:
    auth: true
    starttls:
      enable: true
    host: sandbox.smtp.mailtrap.io
    port: 587
    ssl:
      trust: sandbox.smtp.mailtrap.io